### ISSUE TITLE
[Bug] ImportError: libtiff.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Malix82** [qmk/qmk_cli#139]
### Describe the Bug

can't execute qmk -command on arch linux. it produces following output:

```
% qmk                                        
Error: %s: %s ('ImportError', ImportError('libtiff.so.5: cannot open shared object file: No such file or directory'))
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qmk_cli/script_qmk.py", line 76, in main
    import qmk.cli  # noqa
  File "/home/malix/qmk_firmware/lib/python/qmk/cli/__init__.py", line 244, in <module>
    __import__(subcommand)
  File "/home/malix/qmk_firmware/lib/python/qmk/cli/painter/__init__.py", line 1, in <module>
    from . import convert_graphics
  File "/home/malix/qmk_firmware/lib/python/qmk/cli/painter/convert_graphics.py", line 7, in <module>
    from qmk.painter import render_header, render_source, render_license, render_bytes, valid_formats
  File "/home/malix/qmk_firmware/lib/python/qmk/painter.py", line 6, in <module>
    from PIL import Image, ImageOps
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
```

using the libtiff and qmk package provided in the repos ( https://archlinux.org/packages/extra/x86_64/libtiff/ 

* qmk 1.1.1-1 - https://archlinux.org/packages/community/any/qmk/
* libtiff 4.5.0-1 - https://archlinux.org/packages/extra/x86_64/libtiff/

installed libtiff is version has following .so files

```
libtiff /usr/lib/libtiff.so
libtiff /usr/lib/libtiff.so.6
libtiff /usr/lib/libtiff.so.6.0.0
libtiff /usr/lib/libtiffxx.so
libtiff /usr/lib/libtiffxx.so.6
libtiff /usr/lib/libtiffxx.so.6.0.0
```

### Additional Context?

might be off topic, but why does the cli app even need images?

**Comment by fauxpark** [comment]
The Arch package is not maintained by us. Please file an issue over there.

Pillow is required for [Quantum Painter](https://docs.qmk.fm/#/quantum_painter).
