### ISSUE TITLE
[Bug] Existing `~/qmk_firmware` breaks CLI

### ISSUE THREAD

**Issue by maciek134** [qmk/qmk_cli#177]
### Describe the Bug

I had an old clone of the qmk firmware repo in `~/qmk_firmware` (from before the CLI repo existed looking at dates) which resulted in this error on running any commands:

```console
$ qmk setup
Traceback (most recent call last):
  File "/usr/bin/qmk", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/qmk_cli/script_qmk.py", line 76, in main
    import qmk.cli  # noqa
    ^^^^^^^^^^^^^^
  File "/home/klh/qmk_firmware/lib/python/qmk/cli/__init__.py", line 193, in <module>
    __import__(subcommand)
  File "/home/klh/qmk_firmware/lib/python/qmk/cli/console.py", line 261, in <module>
    @cli.subcommand('Acquire debugging information from usb hid devices.', hidden=False if cli.config.user.developer else True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klh/.local/lib/python3.12/site-packages/milc/milc.py", line 708, in subcommand_function
    return self.add_subcommand(handler, description, hidden=hidden, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klh/.local/lib/python3.12/site-packages/milc/milc.py", line 689, in add_subcommand
    self.subcommands[name] = SubparserWrapper(self, name, self._subparsers.add_parser(name, **kwargs))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1219, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument {config,clone,console,env,setup,c2json,chibios-confmigrate,clean,compile}: conflicting subparser: console
```

Not the most user-friendly message - not sure if it can be handled better since I don't know Python that well.

**Comment by fauxpark** [comment]
You need to update your repo.
