### ISSUE TITLE
`qmk setup` crashes on W10

### ISSUE THREAD

**Issue by WillyKaze** [qmk/qmk_cli#30]
Got this when running `qmk setup`

```bash
WillyKaze@LUNES MINGW64 /d/Users/WillyKaze/repos/qmk_firmware
$ qmk setup
INFO Found qmk_firmware at D:\Users\WillyKaze\repos\qmk_firmware.

*** Would you like to set 'D:\Users\WillyKaze\repos\qmk_firmware' as your QMK home? [y/n] n

<class 'TypeError'>
ERROR argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.7/site-packages\milc.py", line 635, in __call__
    return self.__call__()
  File "C:/msys64/mingw64/lib/python3.7/site-packages\milc.py", line 640, in __call__
    return self._entrypoint(self)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\qmk_cli\subcommands\setup.py", line 62, in setup
    subprocess.run(doctor_cmd)
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
```

Editing the `subcommands/setup.py` fixed this issue at line 54:

```py

    # Run `qmk_firmware/bin/qmk doctor` to check the rest of the environment out
    qmk_bin = cli.args.home / 'bin/qmk'
    doctor_cmd = [sys.executable, str(qmk_bin), 'doctor'] # <<<<

    if cli.args.yes:
        doctor_cmd.append('--yes')
```

**Comment by skullydazed** [comment]
Are you able to test #32 easily?

Otherwise, or if you test #32 and it works, you can also upgrade to python 3.8 to fix the problem.
