### ISSUE TITLE
[Bug] Getting "FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'" when I try and run qmk setup

### ISSUE THREAD

**Issue by thisisian** [qmk/qmk_cli#45]
I follow the instructions on the readme and get this error when I run `qmk setup`:

```Traceback (most recent call last):
  File "/home/ian/.local/bin/./qmk", line 8, in <module>
    sys.exit(main())
  File "/home/ian/.local/lib/python3.9/site-packages/qmk_cli/script_qmk.py", line 60, in main
    broken_modules = find_broken_requirements('requirements.txt')
  File "/home/ian/.local/lib/python3.9/site-packages/qmk_cli/helpers.py", line 21, in find_broken_requirements
    with Path(requirements).open() as fd:
  File "/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

## Additional Context

Using Arch Linux. 
Python 3.9.2
pip 21.0.1 from /home/ian/.local/lib/python3.9/site-packages/pip (python 3.9)

I also tried the Arch package but had the same result.

**Comment by skullydazed** [comment]
I'm not able to reproduce this bug on Debian, and I'm not able to test in an Arch container because I'm running into this bug: https://bugs.archlinux.org/task/69563

Can you include the full output from running this command, including the command line itself? That might shed more light on what is happening on your machine.

**Comment by skullydazed** [comment]
I've just released qmk 0.0.41, which probably doesn't fix your problem but should fail more gracefully and give us more information about your situation. Can you give that a try too?

**Comment by thisisian** [comment]
Here's my output:
```[ian@polybus ~]$ python -m pip install --ugrade qmk
Defaulting to user installation because normal site-packages is not writeable

Collecting qmk
  Downloading qmk-0.0.41-py2.py3-none-any.whl (9.4 kB)
Requirement already satisfied: milc>=1.0.8 in ./.local/lib/python3.9/site-packages (from qmk) (1.2.0)
Requirement already satisfied: hjson in ./.local/lib/python3.9/site-packages (from qmk) (3.0.2)
Requirement already satisfied: hjson in ./.local/lib/python3.9/site-packages (from qmk) (3.0.2)
Requirement already satisfied: jsonschema>=3 in ./.local/lib/python3.9/site-packages (from qmk) (3.2.0)
Requirement already satisfied: appdirs in ./.local/lib/python3.9/site-packages (from qmk) (1.4.4)
Requirement already satisfied: yapf in ./.local/lib/python3.9/site-packages (from qmk) (0.31.0)
Requirement already satisfied: dotty-dict in ./.local/lib/python3.9/site-packages (from qmk) (1.3.0)
Requirement already satisfied: colorama in ./.local/lib/python3.9/site-packages (from qmk) (0.4.4)
Requirement already satisfied: pygments in ./.local/lib/python3.9/site-packages (from qmk) (2.8.1)
Requirement already satisfied: argcomplete in ./.local/lib/python3.9/site-packages (from qmk) (1.12.2)
Requirement already satisfied: flake8 in ./.local/lib/python3.9/site-packages (from qmk) (3.9.0)
Requirement already satisfied: nose2 in ./.local/lib/python3.9/site-packages (from qmk) (0.10.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./.local/lib/python3.9/site-packages (from jsonschema>=3->qmk) (0.17.3)
Requirement already satisfied: setuptools in ./.local/lib/python3.9/site-packages (from jsonschema>=3->qmk) (54.2.0)
Requirement already satisfied: six>=1.11.0 in ./.local/lib/python3.9/site-packages (from jsonschema>=3->qmk) (1.15.0)
Requirement already satisfied: attrs>=17.4.0 in ./.local/lib/python3.9/site-packages (from jsonschema>=3->qmk) (20.3.0)
Requirement already satisfied: setuptools_scm in ./.local/lib/python3.9/site-packages (from dotty-dict->qmk) (6.0.1)
Requirement already satisfied: pyflakes<2.4.0,>=2.3.0 in ./.local/lib/python3.9/site-packages (from flake8->qmk) (2.3.1)
Requirement already satisfied: pycodestyle<2.8.0,>=2.7.0 in ./.local/lib/python3.9/site-packages (from flake8->qmk) (2.7.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in ./.local/lib/python3.9/site-packages (from flake8->qmk) (0.6.1)
Requirement already satisfied: coverage>=4.4.1 in ./.local/lib/python3.9/site-packages (from nose2->qmk) (5.5)
Installing collected packages: qmk
[ian@polybus ~]$ qmk setup
Traceback (most recent call last):
  File "/home/ian/.local/bin/qmk", line 8, in <module>
    sys.exit(main())
  File "/home/ian/.local/lib/python3.9/site-packages/qmk_cli/script_qmk.py", line 73, in main
    broken_modules, broken_dev_modules = broken_module_imports()
  File "/home/ian/.local/lib/python3.9/site-packages/qmk_cli/helpers.py", line 14, in broken_module_imports
    broken_modules = find_broken_requirements('requirements.txt')
  File "/home/ian/.local/lib/python3.9/site-packages/qmk_cli/helpers.py", line 40, in find_broken_requirements
    with Path(requirements).open() as fd:
  File "/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by skullydazed** [comment]
I've added more checks further up the stack, can you give 0.0.42 a try?

**Comment by thisisian** [comment]
After upgrading as above and running `qmk setup` again I got:
```/home/ian/qmk_firmware exists but is not a qmk_firmware clone!
Could not find qmk firmware```

I deleted the qmk_firmware folder and ran `qmk setup` again and the setup reported it was successful. Thanks for the help!
