### ISSUE TITLE
qmk setup fails when QMK_HOME has ~ in the path

### ISSUE THREAD

**Issue by Duckle29** [qmk/qmk_cli#9]
setting the environment variable to a path with a tilde in it makes qmk setup fail.

`export QMK_HOME='~/.qmk_firmware'`

```
Traceback (most recent call last):
  File "/home/mikkel/.local/bin/qmk", line 10, in <module>
    sys.exit(main())
  File "/home/mikkel/.local/lib/python3.7/site-packages/qmk_cli/script_qmk.py", line 77, in main
    import qmk.cli
ModuleNotFoundError: No module named 'qmk'
```

this isn't a problem if the absolute path is given.

**Comment by skullydazed** [comment]
This should be fixed in the latest release.
